SportsStore.WebUI/Models/CartIndexViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string returnURL { get; set; }
    }
}

SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); } }
    }
}

SportsStore.WebUI/Models/ProductsListViewModel.cs
using SportsStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

SportsStore.WebUI/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IProductRepository repo, IOrderProcessor orderProcessor)
        {
            repository = repo;
            this.orderProcessor = orderProcessor;

        }

        public ViewResult Index(Cart cart, string returnURL)
        {
            return View(new CartIndexViewModel {
                Cart = cart,
                returnURL = returnURL
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout(Cart cart)
        {
                return View(new ShippingDetail());            
        }

        [HttpPost]
        public ViewResult Checkout(ShippingDetail shippingDetails, Cart cart)
        {
            if (cart.AllCartLines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, Your Cart is empty");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.ClearCart();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
                
        }

        public RedirectToRouteResult AddToCart(Cart cart,int productID, string returnURL)
        {
            Product product = repository.Products
                            .FirstOrDefault(p => p.ProductID == productID);
            if (product != null)
            {
                cart.AddItem(product,1);
            }

            return RedirectToAction("Index", new { returnURL });
                            
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productID, string returnURL)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productID);
            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnURL });
        }
    }
}

SportsStore.WebUI/Controllers/NavController.cs
using SportsStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null, bool horizontalLayout = false)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            string viewName = horizontalLayout ? "MenuHorizontal" : "Menu";

            return PartialView(viewName,categories);
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int pageSize = 4;

        public ProductController(IProductRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category== null ? repository.Products.Count(): repository.Products.Where(p => p.Category == category).Count()
                },

                CurrentCategory = category
            };

            return View(model);
        }
    }
}

SportsStore.WebUI/Views/Cart/Checkout.cshtml
@model SportsStore.Domain.Entities.ShippingDetail

@{
    ViewBag.Title = "Sport Store: Checkout";
}

<h2>Checkout Out</h2>
<p>Please enter your address and we will ship these items right away</p>

@using(Html.BeginForm()){
@Html.ValidationSummary()
<h3>Ship to</h3>
<div class="form-group">
    <label>Name:</label>
    @Html.TextBoxFor(x=>x.Name, new { @class = "form-control"})
</div>
<h3>Address</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }
    <h3>Options</h3>
<div class="checkbox">
    <label>
    @Html.EditorFor(x => x.GiftWrap)
        Gift wrap these items
        </label>   
</div>
    <div class="text-center">
        <input type="submit" class="btn btn-primary" value="Complete Order"/>
    </div>
}


SportsStore.WebUI/Views/Cart/Completed.cshtml

@{
    ViewBag.Title = "Sport Store: Order Completed";
}

<h2>Thanks!</h2>

Thanks for placing your order. We'll ship your items as soon as possible.


SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Sports Store - Your Cart";
}
<h2>Your Cart</h2>
<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Quanity</th>
            <th class="text-right">Price</th>
            <th class="text-right">SubTotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cart.AllCartLines)
        {
          <tr>
              <td>@item.Product.Name</td>
              <td>@item.Quantity</td>
              <td class="text-right">@item.Product.Price.ToString("C")</td>
              <td class="text-right">@((item.Product.Price * item.Quantity).ToString("C"))</td>
              <td>
                 @using (Html.BeginForm("RemoveFromCart", "Cart")){
                  @Html.Hidden("ProductID", item.Product.ProductID)
                  @Html.HiddenFor(x => x.returnURL)
                  <input class="btn btn-warning btn-sm pull-right" type="submit" value="Remove"/>
                  }
              </td>
          </tr>
        }        
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total</td>
            <td class="text-right">@Model.Cart.ComputeTotalValue().ToString("C")</td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.returnURL">Continue Shoping</a>
    @if (Model.Cart.AllCartLines.Count() > 0)
    {
         @Html.ActionLink("Checkout Now", "Checkout", null, new { @class = "btn btn-primary" })
    }
</div>



SportsStore.WebUI/Views/Cart/Summary.cshtml
@model SportsStore.Domain.Entities.Cart

<div class="navbar-right hidden-xs">
    @Html.ActionLink("Checkout", "Index", "Cart",
    new { returnURL = Request.Url.PathAndQuery },
    new { @class = "btn btn-primary navbar-btn" })
</div>
<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index","Cart", new { returnURL = Request.Url.PathAndQuery }) class="btn btn-primary navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>
<div class="navbar-text navbar-right hidden-xs">
    <b>YOUR CART:</b>
    @Model.AllCartLines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("C")
</div>
<div class="navbar-text navbar-right visible-xs">
    @Model.AllCartLines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("C")
</div>

SportsStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home","List","Product",null,new { @class = "btn btn-block btn-default btn-lg" + (ViewBag.SelectedCategory == null ? " btn-primary" : "") })

@foreach (var link in Model)
{
    @Html.RouteLink(link,
                    new
                    {
                        Controller = "Product",
                        action = "List",
                        category = link,
                        page = 1,
                    }, new
                    {
                        @class = "btn btn-block btn-default btn-lg"
                        + (link == ViewBag.SelectedCategory? " btn-primary" : "")
                    })
}

SportsStore.WebUI/Views/Nav/MenuHorizontal.cshtml
@model IEnumerable<string>

<div class="btn-group btn-group-sm btn-group-justified">
    @Html.ActionLink("Home", "List", "Product", null, new { @class = "btn btn-default btn-sm" + (ViewBag.SelectedCategory == null ? " btn-primary" : "")})
@foreach(var link in Model) {
        @Html.RouteLink( link, new
        {
            controller = "Product",
            action = "List",
            category = link,
            page = 1
        }, new
        {
            @class = "btn btn-default btn-sm"
        + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
        })
}
</div>

SportsStore.WebUI/Views/Product/List.cshtml
@model SportsStore.WebUI.Models.ProductsListViewModel


@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
    @Html.Partial("ProductSummary", p)
}
<div>
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x , category = Model.CurrentCategory}))
</div>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>

    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart" />
        </div>
    }
        <span class="lead">@Model.Description</span>
 </div>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <style>
        .navbar-right{
            float:right !important;
            margin-right: 15px ;
            margin-left: 15px;
        }

    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
       <span class="hidden-xs">SPORT STORE</span>
            <div class="visible-xs">SPORT</div>
            <div class="visible-xs">STORE</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu","Nav",new { horizontalLayout = true })
    </div>
     <div class="row panel">
         <div id="Categories" class="col-sm-2 col-sm-offset-1 hidden-xs">
             @Html.Action("Menu", "Nav")
         </div>
         <div class="col-xs-12 col-sm-8">
        @RenderBody()
          </div>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>